### ISSUE TITLE
Mobile did not display on Web page

### ISSUE THREAD

**Issue by pigass0512** [NetrisTV/ws-scrcpy#22]
The service run successfully, but the terminal display "error: failed to start server". And the mobile screen can not display on web page after I click Native stream hyperlink. How can I fix it? Can someone help me, please?
Terminal error msg
![擷取2](https://user-images.githubusercontent.com/62682766/83249615-6b655680-a1d9-11ea-895b-f67bfd83f943.PNG)

Web page display like below pic
![擷取](https://user-images.githubusercontent.com/62682766/83249357-0873bf80-a1d9-11ea-80d5-5a8ca7a86c28.PNG)

**Comment by drauggres** [comment]
Hi. Please try latest version from `master` branch, I pushed some changes.

**Comment by pigass0512** [comment]
> Hi. Please try latest version from `master` branch, I pushed some changes.

Hi @drauggres master, I'd using the latest branch. but the device screen still not display on my web page..
npm version is 6.13.4
nodejs version is 8.17.0
Do I need to provide other info?

**Comment by drauggres** [comment]
Do you still have: `error: failed to start server` after `npm start`?

**Comment by pigass0512** [comment]
> Do you still have: `error: failed to start server` after `npm start`?

Hi @drauggres master,
No, the error was fix after I using the latest branch!
Currently, another issue is that my web page did not display my mobile device screen..

**Comment by drauggres** [comment]
Can you verify that the `ip` parameter in the stream link contains correct IP address of the device and that device is available via that IP address from the place where you run browser?

**Comment by pigass0512** [comment]
Hi @drauggres master,
Yes, the device IP is the same as stream link, and the device and browser are  in the same network.
The URL as below:
http://10.44.147.108:8000/#!showFps=true&action=stream&udid=MY_DEVICE_UDID&decoder=native&ip=10.44.147.25&port=8886

**Comment by fotiDim** [comment]
I am having the same issue. I am trying with the emulator and I did run `adb forward tcp:8886 tcp:8886`

**Comment by drauggres** [comment]
@fotiDim You need to change `ip` parameter to `127.0.0.1` (and reload the page) because you forwarded port to your localhost.

**Comment by drauggres** [comment]
@pigass0512 It possible that there are some network issues or problem with scrcpy-server.

1. Connect device to your PC (it should be visible in the output of `adb devices`)
2. Run `adb forward tcp:8886 tcp:8886`
3. Open `stream` link 
4. Change `ip` parameter to `127.0.0.1`
5. Reload the page

Have you tried to use original scrcpy with this device? Does it work?

**Comment by pigass0512** [comment]
> @pigass0512 It possible that there are some network issues or problem with scrcpy-server.
> 
> 1. Connect device to your PC (it should be visible in the output of `adb devices`)
> 2. Run `adb forward tcp:8886 tcp:8886`
> 3. Open `stream` link
> 4. Change `ip` parameter to `127.0.0.1`
> 5. Reload the page
> 
> Have you tried to use original scrcpy with this device? Does it work?

The method doesn't seems work to me..the mobile still not display on my web page..
Is the URL correct? http://10.44.147.108:8000/#!showFps=true&action=stream&udid=MY_DEVICE_UDID&decoder=native&ip=127.0.0.1&port=8886
I also tried the original scrcpy with the device, and it works!

**Comment by drauggres** [comment]
The URL looks like correct. Do you have the same problem with other decoders?

**Comment by pigass0512** [comment]
> The URL looks like correct. Do you have the same problem with other decoders?

Yes, I had try all decode method, and got the same problem.

**Comment by fotiDim** [comment]
@drauggres your suggestion did the trick for me. Is there any way to automate this?

**Comment by drauggres** [comment]
@pigass0512 Sorry, I'm out of ideas.

@fotiDim Looks like [someone](https://github.com/jizhang1/ws-scrcpy/commit/8f1ff1a13a122cee7e481b926ac36bf7494f1b52) already working on this.

**Comment by pigass0512** [comment]
@drauggres okay..thanks for your help..does npm and nodejs version will have impact with building service?
Hi @fotiDim, what's your npm and nodejs version? Can you provide your info to me, please?

**Comment by fotiDim** [comment]
@pigass0512 
```
fotidim@Foti-rMBP ~ % npm --version
6.14.4
fotidim@Foti-rMBP ~ % node --version
v10.20.1
````

**Comment by drauggres** [comment]
No, npm and node are not related to this problem.
All communications on "stream" page (except, of course, static files) are between your browser and WebSocket server integrated in scrcpy. You should see `websocket` connection in "DevTools".

**Comment by pigass0512** [comment]
@drauggres It's very strange that I can run old version(0.1.0) successfully, but after I clone latest branch then I can not run the service anymore...lol

**Comment by drauggres** [comment]
New version is incompatible with previous, but they both use the same port (8886).
It's possible that you have runnig old server on the device, but new client.
Try to reboot the device, or manually kill `app_process`.

**Comment by pigass0512** [comment]
@drauggres After I reboot my device, it works!!!!!! You really do me a favor!!!!! Thanks!

**Comment by drauggres** [comment]
I'm glad we solved this.
